# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_senzor_temp.xdc

# Block Designs: bd/design_senzor/design_senzor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_senzor || ORIG_REF_NAME==design_senzor} -quiet] -quiet

# IP: bd/design_senzor/ip/design_senzor_i2c_read_0_0/design_senzor_i2c_read_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_senzor_i2c_read_0_0 || ORIG_REF_NAME==design_senzor_i2c_read_0_0} -quiet] -quiet

# IP: bd/design_senzor/ip/design_senzor_afis_0_0/design_senzor_afis_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_senzor_afis_0_0 || ORIG_REF_NAME==design_senzor_afis_0_0} -quiet] -quiet

# IP: bd/design_senzor/ip/design_senzor_i2c_master_0_0/design_senzor_i2c_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_senzor_i2c_master_0_0 || ORIG_REF_NAME==design_senzor_i2c_master_0_0} -quiet] -quiet

# IP: bd/design_senzor/ip/design_senzor_controler_0_0/design_senzor_controler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_senzor_controler_0_0 || ORIG_REF_NAME==design_senzor_controler_0_0} -quiet] -quiet

# XDC: d:/FPGA/afisare_temperatura_i2c/afisare_temperatura_i2c.gen/sources_1/bd/design_senzor/design_senzor_ooc.xdc
